# Generated by Django 4.2.11 on 2024-03-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("shortened", models.CharField(max_length=150)),
                ("title", models.TextField()),
                ("views", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
